-- MySQL Script generated by MySQL Workbench
-- Thu Nov 24 15:11:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema backtrip
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema backtrip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `backtrip` DEFAULT CHARACTER SET utf8 ;
USE `backtrip` ;

-- -----------------------------------------------------
-- Table `backtrip`.`Epoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backtrip`.`Epoque` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `date` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backtrip`.`type_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backtrip`.`type_article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backtrip`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backtrip`.`article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `Epoque_id` INT NOT NULL,
  `type_article_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_article_Epoque_idx` (`Epoque_id` ASC) VISIBLE,
  INDEX `fk_article_type_article1_idx` (`type_article_id` ASC) VISIBLE,
  CONSTRAINT `fk_article_Epoque`
    FOREIGN KEY (`Epoque_id`)
    REFERENCES `backtrip`.`Epoque` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_type_article1`
    FOREIGN KEY (`type_article_id`)
    REFERENCES `backtrip`.`type_article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backtrip`.`formule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backtrip`.`formule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backtrip`.`tarif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backtrip`.`tarif` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `montant` INT NOT NULL,
  `formule_id` INT NOT NULL,
  `article_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tarif_formule1_idx` (`formule_id` ASC) VISIBLE,
  INDEX `fk_tarif_article1_idx` (`article_id` ASC) VISIBLE,
  CONSTRAINT `fk_tarif_formule1`
    FOREIGN KEY (`formule_id`)
    REFERENCES `backtrip`.`formule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarif_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `backtrip`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backtrip`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backtrip`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(250) NOT NULL,
  `lastName` VARCHAR(250) NOT NULL,
  `e_mail` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backtrip`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backtrip`.`commande` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commande_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_commande_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `backtrip`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backtrip`.`article_has_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backtrip`.`article_has_commande` (
  `article_id` INT NOT NULL,
  `commande_id` INT NOT NULL,
  `quantite` INT NOT NULL,
  PRIMARY KEY (`article_id`, `commande_id`),
  INDEX `fk_article_has_commande_commande1_idx` (`commande_id` ASC) VISIBLE,
  INDEX `fk_article_has_commande_article1_idx` (`article_id` ASC) VISIBLE,
  CONSTRAINT `fk_article_has_commande_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `backtrip`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_has_commande_commande1`
    FOREIGN KEY (`commande_id`)
    REFERENCES `backtrip`.`commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
